version: "3.7"

services:
  django_polls:
    image: django_polls:dev
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: django_polls-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app/
    ports:
      - 5000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12.0-alpine
    container_name: django_polls_db-dev
    environment:
      POSTGRES_USER: django_polls
      POSTGRES_PASSWORD: insecure_password
      POSTGRES_DB: django_polls-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
