version: "3.7"

services:
  django_polls:
    image: django_polls:prod
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile
    container_name: django_polls-prod
    command: gunicorn django_polls.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ../.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: django_polls_db-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.prod.db
  nginx:
    build: ../nginx
    container_name: django_polls_nginx-prod
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - django_polls

volumes:
  postgres_data:
  static_volume:
